name: "Setup MSSQL AdventureWorksLT Database"
branding:
  icon: "database"
  color: "yellow"
inputs:
  sa-password:
    description: "The SA password for the SQL instance"
    required: true
  version:
    description: "The version of the SQL instance"
    required: false
    default: "2022"
runs:
  using: "composite"
  steps:

    - name: Setup MSSQL
      uses: openentity/setup-mssql@v1
      with:
          components: sqlcmd,sqlengine
          sa-password: "${{ inputs.sa-password }}"
          version: "${{ inputs.version }}"

    - shell: pwsh
      run: |
        $backupFile = "${{ github.action_path }}/mssql${{ inputs.version }}/adventureworkslt.bak"
        echo "Restoring database from $backupFile..."

        sqlcmd -S localhost -d master -C  -U sa -P "${{ inputs.sa-password }}" -Q "SELECT name AS LogicalName, type_desc AS FileType, physical_name AS FilePath FROM sys.database_files;"

        sqlcmd -S localhost -d master -C  -U sa -P "${{ inputs.sa-password }}" -Q "RESTORE DATABASE [AdventureWorksLT] FROM DISK = '$backupFile' WITH MOVE 'AdventureWorksLT${{ inputs.version }}_Data' TO 'AdventureWorksLT_Data.mdf', MOVE 'AdventureWorksLT${{ inputs.version }}_log' TO 'AdventureWorksLT_Log.ldf'"

        echo "Done installing AdventureWorksLT database."
