name: "Setup MSSQL AdventureWorksLT Database"
branding:
  icon: "database"
  color: "yellow"
inputs:
  sa-password:
    description: "The SA password for the SQL instance"
    required: true
  version:
    description: "The version of SQL Server to use (2022)"
    required: false
    default: "2022"

runs:
  using: "composite"
  steps:

    - name: Setup MSSQL
      uses: openentity/setup-mssql@v1
      with:
          components: sqlcmd,sqlengine
          sa-password: "${{ inputs.sa-password }}"
          version: "${{ inputs.version }}"

    - shell: pwsh
      run: |
        $version = "16"

        $backupFile = "${{ github.action_path }}/mssql${{ inputs.version }}/adventureworkslt.bak"
        echo "Restoring database from $backupFile..."

        $db = "AdventureWorksLT${{ inputs.version }}"
        $dbData = "$db_Data"
        $dbLog = "$db_log"
        $serverFolder = "C:\Program Files\Microsoft SQL Server\MSSQL$version.SQLEXPRESS\MSSQL\DATA"
        $mdf = "$serverFolder\AdventureWorksLT_Data.mdf"
        $ldf = "$serverFolder\AdventureWorksLT_Log.ldf"

        echo dbData = "$dbData"
        echo dbLog = "$dbLog"
        echo mdf = "$mdf"
        echo ldf = "$ldf"

        sqlcmd -S localhost -d master -C  -U sa -P "${{ inputs.sa-password }}" -Q "RESTORE DATABASE [AdventureWorksLT] FROM DISK = '$backupFile' WITH MOVE '$dbData' TO '$mdf', MOVE '$dbLog' TO '$ldf'"

        echo "Done installing AdventureWorksLT database."
